### ISSUE TITLE
Automatically generate help

### ISSUE THREAD

**Issue by gsingh93** [zcdziura/pirate#2]
I know this is in the TODO list, but I wanted to make an issue to show that this is a feature I'm waiting for. I like how concise and simple this API is, but automatically generating the help text is a must have for me.

**Comment by zcdziura** [comment]
I'm working on an update now, hopefully I'll be able to push something up soon. Thank you for showing interest!

**Comment by zcdziura** [comment]
1c75b5354e0da81bec2d4b60fe5174af99a7c115

**Comment by zcdziura** [comment]
Just pushed up v1.0 of the project, which features the auto-generated help text feature. Check it out and let me know what you think!
